### ISSUE TITLE
Latin America Dataset

### ISSUE THREAD

**Issue by pablodz** [Geofgabriel/CoronaPlots#1]
Hola, vi que estás realizando un análisis para latinoamérica, te comento que tenemos un repositorio centralizado por subdivision de país. 

Te dejo el repositorio: https://github.com/DataScienceResearchPeru/covid-19_latinoamerica
No olvides dejar tu estrellita, gracias por tu tiempo.

**Comment by Geofgabriel** [comment]
Hola!

Gracias por la información...ya miro el repositorio. Obvio que te dejo la estrellita!
Saludos
